### PR TITLE
add Angular test example

### PR DESCRIPTION
**Pull request by schuchard**
- add Angular spec
- add necessary packages

### CODE REVIEW

**Comment by schuchard** [comment]
I had to add and modify a few deps to get things working with Angular and Typescript. Let me know if anything needs to be adjusted.

**Review by kentcdodds — APPROVED** [review]
Looks good! Thank you so much!

**Comment by kentcdodds** [comment]
Hey @schuchard,

I'm not sure what's up, but this test passes fine once, but if I make any edits to the file in watch mode it breaks. Any ideas?

angular

**Comment by schuchard** [comment]
Hmm, I just pulled latest from master and was unable to reproduce. I'm running node 8.11.1, and npm 6.3.0. From your video, I'm curious what the warning is on `AppComponent`?

Here's my "works on my machine" :) 
https://drive.google.com/file/d/1yMDEL4adasw56BWiA0Ouwots_QJG_4eF/view?usp=sharing

It looks like the change detection is not running on the second round since the counter value is remaining at `0`. Though that should be handled with:

```providers: [{provide: ComponentFixtureAutoDetect, useValue: true}],```

I also tried spreading `getQueriesForElement` and it still worked.

Maybe a [jest cache](https://jestjs.io/docs/en/cli.html#clearcache) issue? Happy to debug if you think of anything else.

**Comment by kentcdodds** [comment]
I'm not too concerned. Most people who make use of this knowledge will likely not use Jest but will use angular-cli and therefore wont run into these issues.

**Pull request merged**
